server:
  port: 8081

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.xinyue.blog.model    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: cloud-blog-admin
  datasource:
    type: "com.alibaba.druid.pool.DruidDataSource"
    druid:
      url: "jdbc:mysql://localhost:3306/website?useUnicode=yes&characterEncoding=UTF-8&useTimezone=true&serverTimezone=UTC"
      username: "xinyue"
      password: "xinyue"
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      validation-query: "SELECT 1"
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: "stat, wall"
      connect-properties: "druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000"

  jpa:
    properties:
      hibernate.hbm2ddl.auto: update
  servlet:
    multipart:
      max-file-size: "10MB"
      max-request-size: "30MB"
  config:
    name: "my-blog"

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
    com:
      xinyue:
        blog:
          dao:
            mybaits: DEBUG

druid:
  userName: xinyue
  password: xinyue0706

